<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HardwareMonitor.Windows.UI</RootNamespace>
    <AssemblyName>HardwareMonitor</AssemblyName>
    <ApplicationIcon>HardwareMonitor.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Update="HardwareMonitor.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareMonitor.Windows.Core\HardwareMonitor.Windows.Core.csproj" />
  </ItemGroup>

</Project>
