<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>HardwareMonitor.Windows</RootNamespace>
    <AssemblyName>HardwareMonitor.Windows</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardwareMonitor.Windows.Core\HardwareMonitor.Windows.Core.csproj" />
  </ItemGroup>

</Project>
